apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: fixpanel-staging-cert
spec:
  # Secret names are always required.
  secretName: letsencrypt-staging-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  organization:
    - jetstack
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - fixpanel.org
    - fleet.fixpanel.org
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-staging
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
