apiVersion: v1
kind: PersistentVolume
metadata:
  # This is the name used by the quickstart guide
  name: elasticsearch-data-quickstart-es-default-0
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /Users/kaz/elasticsearch/
