---
# =========== PACKS DEFINED HERE ==============
apiVersion: v1
kind: pack
spec:
  name: Security Best Practices
  queries:
    - query: kolide_best_practices
      name: kolide_best_practices_snapshot
      interval: 240
      snapshot: true
      blacklist: false
      # if the query uses too much resources, it will be blacklisted and stopped for 1 day
      # i.e. it won't run for a day
      # the lower the interval, the more likely it'll be blacklisted
---
# ================== QUERIES DEFINED HERE =======================
# To insert a query into a pack it is referenced by 'name', so ensure the name
# is descriptive
apiVersion: v1
kind: query
spec:
  name: kolide_best_practices
  description: Checks if the endpoint is configured to follow some best security practices
  query: SELECT * FROM kolide_best_practices;
  support:
    launcher: 0.3.0
  blacklist: false
---

