---
apiVersion: v1
kind: query
spec:
  name: firewall-enabled-dar
  description: Returns 1 if the firewall is enabled, 0 if not
  query: SELECT global_state AS compliant FROM alf;
  support:
    platforms:
      - darwin
---
apiVersion: v1
kind: query
spec:
  name: disk-encryption-enabled-dar
  description: Returns 1 if full disk-encryption is enabled, 0 if not
  query: SELECT de.encrypted AS compliant FROM mounts m join disk_encryption de ON m.device_alias = de.name WHERE m.path = '/'
  support:
    platforms:
      - darwin
---
apiVersion: v1
kind: query
spec:
  name: password-manager-installed-dar
  description: Counts the number of password managers installed, 0 installed is a failure
  query: >
    SELECT count(bundle_name) as compliant FROM apps WHERE
    LOWER(bundle_name) LIKE '%last%pass%' OR
    LOWER(bundle_name) LIKE '%1password%' OR
    LOWER(bundle_name) LIKE '%dashlane%' OR
    LOWER(bundle_name) LIKE '%enpass%' OR
    LOWER(bundle_name) LIKE '%mitto%' OR
    LOWER(bundle_name) LIKE '%myki%' OR
    LOWER(bundle_name) LIKE '%intuitive%password%' OR
    LOWER(bundle_name) LIKE '%bitwarden%' OR
    LOWER(bundle_name) LIKE '%key%pass%';
  support:
    platforms:
      - darwin
---
apiVersion: v1
kind: query
spec:
  name: screenlock-enabled-dar
  description: Fail if password on lock is enabled or password on lock enables after 5 minutes
  query: select case when enabled=0 or grace_period=-1 or grace_period > 300 then 0 else 1 end as compliant from screenlock;
  support:
    platforms:
      - darwin
---
apiVersion: v1
kind: query
spec:
  name: os-up-to-date-dar
  description: Pass if macOS version is above a certain version. Version must be a string like '2.3.2'
  query: select case when version >= '10.15.5' then 1 else 0 end as compliant from os_version;
  support:
    platforms:
      - darwin
---
apiVersion: v1
kind: query
spec:
  name: auto-update-enabled-dar
  description: Pass if checkCount=3, fail otherwise.
  query: >
    select count(key) as checkCount, case when
    key='AutomaticDownload' and value='true' or
    key='CriticalUpdateInstall' and value='true' or
    key='AutomaticCheckEnabled' and value='true' then 1 else 0 end as compliant
    from preferences where domain='com.apple.SoftwareUpdate' and host='current'
    and compliant=1;
  support:
    platform:
      - darwin
---
apiVersion: v1
kind: query
spec:
  name: remote-login-enabled-dar
  description: Pass if remote_login is disabled (0)
  query: select remote_login from sharing_preferences
  support:
    platform:
      - darwin
---

