apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kolide-fleet.fullname" . }}
  labels:
    app: {{ template "kolide-fleet.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    {{- include "kolide-fleet.labels" . | nindent 4 }}
spec:
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        "helm.sh/hook": post-install, post-upgrade
        "helm.sh/hook-weight": "0"
        "helm.sh/hook-delete-policy": hook-succeeded
      {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: {{ template "kolide-fleet.fullname" . }}
        release: "{{ .Release.Name }}"
    spec:
      volumes:
        - name: fleet-configuration
          configMap:
            name: {{ template "kolide-fleet.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: KOLIDE_AUTH_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "kolide-fleet.fullname" . }}
                  key: fleet.auth.jwt_key
            - name: KOLIDE_MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "kolide-fleet.fullname" . }}
                  key: fleet.mysql.username
            - name: KOLIDE_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "kolide-fleet.fullname" . }}
                  key: fleet.mysql.password
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
            - "fleet"
            - "prepare"
            - "db"
            - "--config"
            - "/etc/fleet/config.yml"
          volumeMounts:
            - name: fleet-configuration
              readOnly: true
              mountPath: /etc/fleet
      restartPolicy: "Never"
      
