apiVersion: v1
kind: Secret
metadata:
  labels:
    app: elasticsearch
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: elastic-credentials
data:
  username: {{ required "A valid Elasticsearch username is required" .Values.elasticCreds.username | b64enc }}
  password: {{ required "A valid Elasticsearch password is required" .Values.elasticCreds.password | b64enc }}