apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kolide-fleet.fullname" . }}
data:
  config.yml: |-
    mysql:
      protocol: tcp
      address: kf-mysql:3306
      # username: <placeholder for secret>
      # password: <placeholder for secret>
      # database: <placeholder for secret>
      tls_cert: ""
      tls_key: ""
      tls_ca: ""
      tls_server_name: ""
      tls_config: ""
      max_open_conns: 50
      max_idle_conns: 50
    redis:
      address: kf-redis-master:6379
      cluster.slaveCount: 0
      master.persistence.enabled: false
      usePassword: false
    server:
      address: 0.0.0.0:8080
      cert: /etc/pki/fleet/tls.crt
      key: /etc/pki/fleet/tls.key
      # default false because load balancer does not require it
      tls: {{ default false .Values.fleet.server.tls }}
      # tlsprofile: modern
      url_prefix: ""
    auth:
      jwt_key: <placeholder for secret>
      bcrypt_cost: 12
      salt_key_size: 24
    app:
      token_key_size: 24
      invite_token_validity_period: 120h0m0s
    session:
      key_size: 64
      duration: 4h0m0s
    osquery:
      node_key_size: 24
      status_log_plugin: filesystem
      result_log_plugin: filesystem
      label_update_interval: 1h0m0s
      detail_update_interval: 1h0m0s
    logging:
      debug: {{ default false .Values.fleet.logging.debug }}
      json: {{ default false .Values.fleet.logging.json }}
      disable_banner: {{ default false .Values.fleet.logging.disable_banner }}
    filesystem:
      status_log_file: {{ .Values.fleet.filesystem.result_volume }}/status.log
      result_log_file: {{ .Values.fleet.filesystem.result_volume }}/result.log
      # when the log gets to 500MB or 28 days, whichever is first
      enable_log_rotation: true
    decorators:
      load:
        - "SELECT uuid AS host_uuid, computer_name FROM system_info"
      always:
        - "SELECT user AS username FROM logged_in_users WHERE user <> '' ORDER BY time LIMIT 1"
      interval:
        3600: "SELECT total_seconds AS uptime FROM uptime"
---

