apiVersion: v1
kind: Service
metadata:
  name: {{ include "kolide-fleet.fullname" . }}
  labels:
    {{- include "kolide-fleet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.fleet.service.type }}
  ports:
    - port: {{ .Values.fleet.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kolide-fleet.selectorLabels" . | nindent 4 }}
