---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: linode-block-storage-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi