# This secret is created on deployment. Thus you can pass in whatever values file you want
# for these secrets, they should be kept separately and outside the repo (not kept publicly anywhere)
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "kolide-fleet.fullname" .}}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "kolide-fleet.fullname" . }}
data:
  fleet.mysql.username: {{ required "A valid MySQL username is required" .Values.mysql.mysqlUser | b64enc }}
  fleet.mysql.password: {{ required "A valid MySQL Password is required" .Values.mysql.mysqlPassword | b64enc }}
  fleet.auth.jwt_key: {{ required "A valid JWT key is required" .Values.fleet.auth.jwt_key | b64enc }}