apiVersion: v1
kind: Secret
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    role: smtp
  name: smtp-auth-secret
stringData:
  # must be in the format of user: \n password: to satisfy elastalert
  smtp_auth.yaml: |-
    user: {{ required "A valid email address is required" .Values.smtp.user }}
    password: {{ required "A valid email password is required" .Values.smtp.password }}