---
apiVersion: v1
kind: query
spec:
  name: disk-encryption-enabled-win
  description: Returns 1 if disk is 100% encrypted with a non-None encryption method, 0 otherwise
  query: >
    SELECT case
    WHEN percentage_encrypted=100 and encryption_method != 'None'
    THEN 1 ELSE 0 END as compliant 
    FROM bitlocker_info;
  support:
    platforms:
      - windows
---
apiVersion: v1
kind: query
spec:
  name: auto-update-enabled-win
  description: Returns 1 if autoupdate health is 'Good', 0 otherwise
  query: select case when autoupdate='Good' then 1 else 0 end as compliant from windows_security_center;
  support:
    platforms:
      - windows
---
apiVersion: v1
kind: query
spec:
  name: firewall-enabled-win
  description: Returns 1 if firewall health is "Good", 0 otherwise
  query: select case when firewall='Good' then 1 else 0 end as compliant from windows_security_center;
  support:
    platforms:
      - windows
---
apiVersion: v1
kind: query
spec:
  name: password-manager-installed-win
  description: "Count of password managers installed"
  query: >
    SELECT count(name) as compliant FROM programs WHERE
    LOWER(name) LIKE '%last%pass%' OR
    LOWER(name) LIKE '%1password%' OR
    LOWER(name) LIKE '%dashlane%' OR
    LOWER(name) LIKE '%enpass%' OR
    LOWER(name) LIKE '%mitto%' OR
    LOWER(name) LIKE '%myki%' OR
    LOWER(name) LIKE '%intuitive%password%' OR
    LOWER(name) LIKE '%bitwarden%' OR
    LOWER(name) LIKE '%gnome%keyring%' OR
    LOWER(name) LIKE '%kee%pass%' OR
    LOWER(name) LIKE '%keeper%' OR
    LOWER(name) LIKE '%meldium%' OR
    LOWER(name) LIKE '%kee%web%';
  support:
    platforms:
      - windows
---
apiVersion: v1
kind: query
spec:
  name: antivirus-health-win
  description: Anti-virus health should be 'Good' to be compliant
  query: select case when antivirus='Good' then 1 else 0 end as compliant from windows_security_center;
  support:
    platforms:
      - windows
---
apiVersion: v1
kind: query
spec:
  name: antispyware-health-win
  description: Anti-spyware health should be 'Good' to be compliant
  query: select case when antispyware='Good' then 1 else 0 end as compliant from windows_security_center;
  support:
    platforms:
      - windows
---

