---
apiVersion: v1
kind: query
spec:
  name: chrome-up-to-date-if-exists-win
  description: Pass if chrome isn't installed or it is installed AND the version is above the version specified
  query: >
    select name, version, case when version >= '83.0.4103.116' then 1 else 0 end as compliant from programs where lower(name) like "%google%chrome%";
  support:
    platforms:
      - windows
---
apiVersion: v1
kind: query
spec:
  name: firefox-up-to-date-if-exists-win
  description: Pass if chrome isn't installed or it is installed AND the version is above the version specified
  query: >
    select name, version, case when version >= '83.0.4103.116' then 1 else 0 end as compliant from programs where lower(name) like "%firefox%";
  support:
    platforms:
      - windows
---
apiVersion: v1
kind: query
spec:
  name: firefox-up-to-date-if-exists-win
  description: Pass if chrome isn't installed or it is installed AND the version is above the version specified
  query: >
    select name, version, case when version >= '83.0.4103.116' then 1 else 0 end as compliant from programs where lower(name) like "%firefox%";
  support:
    platforms:
      - windows