---
apiVersion: v1
kind: query
spec:
  name: chrome-up-to-date-win
  description: Returns 1 if disk is 100% encrypted with a non-None encryption method, 0 otherwise
  query: >
    select name, version, case when version >= '83.0.4103.116' then 1 else 0 end as compliant from programs where lower(name) like "%google%chrome%";
  support:
    platforms:
      - windows
---

