---
apiVersion: v1
kind: query
spec:
  name: disk-encryption-enabled-win
  description: Returns 1 if disk is 100% encrypted with a non-None encryption method, 0 otherwise
  query: >
    SELECT case
    WHEN percentage_encrypted=100 and encryption_method != 'None'
    THEN 1 ELSE 0 END as compliant 
    FROM bitlocker_info;
  support:
    platforms:
      - windows
---
apiVersion: v1
kind: query
spec:
  name: auto-update-enabled-win
  description: Returns 1 if autoupdate health is 'Good', 0 otherwise
  query: select case when autoupdate='Good' then 1 else 0 end as compliant from windows_security_center;
  support:
    platforms:
      - windows
---
apiVersion: v1
kind: query
spec:
  name: firewall-enabled-win
  description: Returns 1 if firewall health is "Good", 0 otherwise
  query: select case when firewall='Good' then 1 else 0 end as compliant from windows_security_center;
  support:
    platforms:
      - windows
---
apiVersion: v1
kind: query
spec:
  name: password-manager-installed-win
  description: "Count of password managers installed"
  query: >
    SELECT count(name) as compliant FROM programs WHERE
    LOWER(name) LIKE '%last%pass%' OR
    LOWER(name) LIKE '%1password%' OR
    LOWER(name) LIKE '%dashlane%' OR
    LOWER(name) LIKE '%enpass%' OR
    LOWER(name) LIKE '%mitto%' OR
    LOWER(name) LIKE '%myki%' OR
    LOWER(name) LIKE '%intuitive%password%' OR
    LOWER(name) LIKE '%bitwarden%' OR
    LOWER(name) LIKE '%key%pass%';
  support:
    platforms:
      - windows
---
apiVersion: v1
kind: query
spec:
  name: os-up-to-date-win
  description: Pass if Windows version is above a certain version. Version must be a string like '2.3.2'
  query: select case when version >= '10.0.19041' then 1 else 0 end as compliant from os_version;
  support:
    platforms:
      - windows
