---
apiVersion: v1
kind: query
spec:
  name: firewall-enabled-dar
  description: Returns 1 if the firewall is enabled, 0 if not
  query: SELECT global_state AS compliant FROM alf;
  support:
    platforms:
      - darwin
---
apiVersion: v1
kind: query
spec:
  name: disk-encryption-enabled-dar
  description: Returns 1 if full disk-encryption is enabled, 0 if not
  query: SELECT de.encrypted AS compliant FROM mounts m join disk_encryption de ON m.device_alias = de.name WHERE m.path = '/'
  support:
    platforms:
      - darwin
---
apiVersion: v1
kind: query
spec:
  name: screenlock-enabled-dar
  description: Fail if password on lock is enabled or password on lock enables after 5 minutes
  query: select case when enabled=0 or grace_period=-1 or grace_period > 300 then 0 else 1 end as compliant from screenlock;
  support:
    platforms:
      - darwin
---
apiVersion: v1
kind: query
spec:
  name: os-auto-update-enabled-dar
  description: Check if automatic update is enabled
  query: >
    select case when
    value='true' then 1 else 0 end as compliant
    from preferences where domain='com.apple.commerce' and host='current' and key='AutoUpdate';
---
apiVersion: v1
kind: query
spec:
  name: remote-login-enabled-dar
  description: Pass (1) if remote_login is disabled
  query: select case when remote_login = 0 then 1 else 0 end as compliant from sharing_preferences
  support:
    platform:
      - darwin
---
apiVersion: v1
kind: query
spec:
  name: password-manager-installed-dar
  description: Counts the number of password managers installed, 0 installed is a failure
  # Keychain not included, since it's already on mac
  query: >
    SELECT count(bundle_name) as compliant FROM apps WHERE
    LOWER(bundle_name) LIKE '%last%pass%' OR
    LOWER(bundle_name) LIKE '%1password%' OR
    LOWER(bundle_name) LIKE '%dashlane%' OR
    LOWER(bundle_name) LIKE '%enpass%' OR
    LOWER(bundle_name) LIKE '%mitto%' OR
    LOWER(bundle_name) LIKE '%myki%' OR
    LOWER(bundle_name) LIKE '%intuitive%password%' OR
    LOWER(bundle_name) LIKE '%bitwarden%' OR
    LOWER(bundle_name) LIKE '%gnome%keyring%' OR
    LOWER(bundle_name) LIKE '%kee%pass%' OR
    LOWER(bundle_name) LIKE '%keeper%' OR
    LOWER(bundle_name) LIKE '%meldium%' OR
    LOWER(bundle_name) LIKE '%kee%web%';
  support:
    platforms:
      - darwin
---
apiVersion: v1
kind: query
spec:
  name: ms-auto-download-on
  description: Checks if MS auto downloads if an update is available
  query: select case when value='AutomaticDownload' then 1 else 0 end as compliant from preferences where domain like '%com.microsoft.autoupdate%' and key='HowToCheck';
  support:
    platform:
      - darwin
---
apiVersion: v1
kind: query
spec:
  name: ms-auto-start-update-daemon
  description: The auto-update daemon should start when opening an MS office application
  query: select case when value='true' then 1 else 0 end as compliant from preferences where domain like '%com.microsoft.autoupdate%' and key='StartDaemonOnAppLaunch';
  support:
    platform:
      - darwin
---

# apiVersion: v1
# kind: query
# spec:
#   name: os-up-to-date-dar
#   description: Pass if macOS version is above a certain version. Version must be a string like '2.3.2'
#   query: select case when version >= '10.15.5' then 1 else 0 end as compliant from os_version;
#   support:
#     platforms:
#       - darwin
# ---
# ---
# apiVersion: v1
# kind: query
# spec:
#   name: auto-check-enabled-dar
#   description: Check if updates are automatically checked for
#   query: >
#     select case when
#     value='true' then 1 else 0 end as compliant
#     from preferences where domain='com.apple.SoftwareUpdate' and host='current' and key="AutomaticCheckEnabled";
#   platform:
#     - darwin
# ---
# apiVersion: v1
# kind: query
# spec:
#   name: auto-update-download-enabled-dar
#   description: Check if updates automatically download
#   query: >
#     select case when
#     value='true' then 1 else 0 end as compliant
#     from preferences where domain='com.apple.SoftwareUpdate' and host='current' and key='AutomaticDownload';
# ---
# apiVersion: v1
# kind: query
# spec:
#   name: critical-update-install-enabled-dar
#   description: Check if critical updates are automatically installed
#   query: >
#     select case when
#     value='true' then 1 else 0 end as compliant
#     from preferences where domain='com.apple.SoftwareUpdate' and host='current' and key='CriticalUpdateInstall';
# ---
