---
apiVersion: v1
kind: query
spec:
  name: chrome-up-to-date-if-exists-dar
  description: Pass if chrome isn't installed or it is installed AND the version is above the version specified
  query: >
    select bundle_name, bundle_short_version, case when bundle_short_version > '6.0.0.0'
    then 1 else 0 end as compliant
    from apps where bundle_name like '%chrome%';
  support:
    platform:
      - darwin
---
apiVersion: v1
kind: query
spec:
  name: opera-up-to-date-if-exists-dar
  description: Pass if opera isn't installed or it is installed AND the version is above the version specified
  query: >
    select bundle_name, bundle_short_version, case when bundle_short_version > '6.0.0.0'
    then 1 else 0 end as compliant
    from apps where bundle_name like '%opera%';
  support:
    platform:
      - darwin
---
apiVersion: v1
kind: query
spec:
  name: firefox-up-to-date-if-exists-dar
  description: Pass if firefox isn't installed or it is installed AND the version is above the version specified
  query: >
    select bundle_name, bundle_short_version, case when bundle_short_version > '6.0.0.0'
    then 1 else 0 end as compliant
    from apps where bundle_name like '%firefox%';
  support:
    platform:
      - darwin
---
apiVersion: v1
kind: query
spec:
  name: tor-up-to-date-if-exists-dar
  description: Pass if tor isn't installed or it is installed AND the version is above the version specified
  query: >
    select bundle_name, bundle_short_version, case when bundle_short_version > '10.0.10'
    then 1 else 0 end as compliant
    from apps where bundle_name like '%tor%browser%';
  support:
    platform:
      - darwin
---
# No need to check safari, updated with OS
